import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import betsRouter from "./bets";
import diceRouter from "./dice";
import coinflipRouter from "./coinflip";
import minesRouter from "./mines";
import rouletteRouter from "./roulette";
import clashRouter from "./clash";
import cashierRouter from "./cashier";
import kchipRouter from "./kchip";
import walletRouter from "./wallet";
import legendsRouter from "./legends";

const router: IRouter = Router();
router.use(healthRouter);
router.use(meRouter);
router.use(kchipRouter);
router.use(walletRouter);
router.use(legendsRouter);
router.use(betsRouter);
router.use(diceRouter);
router.use(coinflipRouter);
router.use(minesRouter);
router.use(rouletteRouter);
router.use(clashRouter);
router.use(cashierRouter);
export default router;
