import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import betsRouter from "./bets";
import diceRouter from "./dice";
import coinflipRouter from "./coinflip";
import minesRouter from "./mines";
import rouletteRouter from "./roulette";
import kchipRouter from "./kchip";
import authRouter from "./auth";
import walletRouter from "./wallet";
import legendsRouter from "./legends";
import dashboardRouter from "./dashboard";
import leaderboardRouter from "./leaderboard";

const router: IRouter = Router();
router.use(healthRouter);
router.use(meRouter);
router.use(kchipRouter);
router.use(authRouter);
router.use(walletRouter);
router.use(legendsRouter);
router.use(dashboardRouter);
router.use(leaderboardRouter);
router.use(betsRouter);
router.use(diceRouter);
router.use(coinflipRouter);
router.use(minesRouter);
router.use(rouletteRouter);
export default router;
